
import sys

data = sys.argv
#print(data)
#raise ValueError(data)


rf = open(data[1], "rb")
contents = rf.read();
lines = contents.split('---')# split by statement
#split by brackets
print(lines)
rf.close()

#print(data)
#raise ValueError(data)
oi = open(data[2], "wb")
oi.write("marti_common_msgs/ServiceHeader srv_header\n")
oi.write(lines[0])
oi.close()

oi = open(data[3], "wb")
oi.write("marti_common_msgs/ServiceHeader srv_header\n")
oi.write(lines[1])
oi.close()

# Write out a wrapper header so we can use and include it like it is a service
# Data 4 has the message name and 5 has the message name
data[5] = data[5].replace(".srv", "")
#raise ValueError(data[4], data[5], data[6])
oi = open(data[6], "wb")
name = data[4] + "_" + data[5]
oi.write("// This file is autogenerated, do not modify\n")
oi.write("#ifndef _" + name + "_TOPIC_SERVICE_H_\n")
oi.write("#define _" + name + "_TOPIC_SERVICE_H_\n")

oi.write("#include <" + data[4] + "/" + data[5] + "Response.h>\n")
oi.write("#include <" + data[4] + "/" + data[5] + "Request.h>\n\n")

oi.write("namespace " + data[4] + "{\n")
oi.write("class " + data[5] + "{ public: \n")
oi.write("typedef " + data[5] + "Response Response;\n")
oi.write("typedef " + data[5] + "Request Request;\n")
oi.write("  Request request; Response response;\n")
oi.write("};\n}\n")

oi.write("#endif")
