#!/usr/bin/env python
import rospy
import swri_rospy
from std_msgs.msg import String

# Decorating the callback with single_threaded will make it wait for its turn
# in the callback queue before executing
@swri_rospy.single_threaded
def callback(data):
    rospy.loginfo(rospy.get_caller_id() + "I heard %s", data.data)

def listener():
    rospy.init_node('listener', anonymous=True)
    rospy.Subscriber('chatter', String, callback)
    # spin() processes the callback queue until the node is stopped
    swri_rospy.spin()

if __name__ == '__main__':
    listener()
