#!/bin/bash

# Launch callgrind with instrumentation disabled.  This allows you
# to target the section of code to profile using the
# CALLGRIND_START_INSTRUMENTATION and CALLGRIND_STOP_INSTRUMENTATION
# macros in your code.  Alternatively, you can toggle instrumentation
# using "callgrind_control -i on/off" in a shell.

# We need to use exec so that the node is the grandchild of
# xterm_prefix.
exec valgrind --tool=callgrind --instr-atstart=no $@