name: CI

on: [push, pull_request]

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: humble, ROS_REPO: testing}
          - {ROS_DISTRO: humble, ROS_REPO: main}
          - {ROS_DISTRO: iron, ROS_REPO: testing}
          - {ROS_DISTRO: iron, ROS_REPO: main}
          - {ROS_DISTRO: jazzy, ROS_REPO: testing}
          - {ROS_DISTRO: jazzy, ROS_REPO: main}
          - {ROS_DISTRO: rolling, ROS_REPO: testing}
          - {ROS_DISTRO: rolling, ROS_REPO: main}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configuring pip
        run: printf "[install]\nbreak-system-packages = true\n" | sudo tee -a /etc/pip.conf
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
