name: CI

on: [push, pull_request]

jobs:
  industrial_ci:
    name: ROS CI
    runs-on: ubuntu-latest

    strategy:
      matrix:
        env:
          - {ROS_DISTRO: noetic, ROS_REPO: testing}

    steps:
      - uses: actions/checkout@v4
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
